import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Box, SimpleGrid, Text } from '@chakra-ui/react'
import { Canvas } from '@react-three/fiber'
import Greeting from './Greeting'
import PlaceAndTime from './PlaceAndTime'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Свадьба Артёма и Юли</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SimpleGrid columns={1}>
          <Greeting />
          <PlaceAndTime />
          <Box bg="blue" height="100vh"></Box>
          <Box bg="green" height="100vh"></Box>
          <Box bg="tomato" height="100vh"></Box>
        </SimpleGrid>
      </main>
    </>
  )
}
